# Generated by Django 6.0.5 on 2026-05-22 10:55

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('nombre_etages', models.IntegerField(default=0)),
                ('date_construction', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeBureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('espace', models.FloatField(default=0.0)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('superficie', models.FloatField(default=0.0)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bureaux', to='gestionBatiment.batiment')),
                ('TypeBureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bureaux', to='gestionBatiment.typebureau')),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telphone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='CM')),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='gestionBatiment.bureau')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats_bureau', to='gestionBatiment.bureau')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='gestionBatiment.client')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats_location', to='gestionBatiment.bureau')),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements', to='gestionBatiment.bureau')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_bureau', to='gestionBatiment.bureau')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='gestionBatiment.contrat')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_location', to='gestionBatiment.bureau')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='gestionBatiment.bureau')),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='gestionBatiment.batiment')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('modePaiement', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='gestionBatiment.client')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='gestionBatiment.bureau')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField()),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='gestionBatiment.bureau')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='gestionBatiment.client')),
            ],
        ),
    ]
