# Generated by Django 6.0.5 on 2026-06-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBatiment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='type_facturation',
            field=models.CharField(choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('SEMESTRIEL', 'Semestriel')], default='MENSUEL', max_length=20),
        ),
    ]
