# Generated by Django 6.0.5 on 2026-06-18 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionBatiment", "0002_contrat_type_facturation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bureau",
            name="statut",
            field=models.CharField(
                choices=[("DISPONIBLE", "Disponible"), ("OCCUPE", "Occupé")],
                default="DISPONIBLE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contrat",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contrat",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contrats_approuves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contrat",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contrats_crees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contrat",
            name="statut_approbation",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Brouillon"),
                    ("PENDING", "En attente"),
                    ("ACTIVE", "Actif"),
                    ("REJECTED", "Rejeté"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="paiement",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paiement",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paiements_approuves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paiement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paiements_crees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paiement",
            name="idempotency_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="statut",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("PAID", "Payé"),
                    ("PENDING_ADMIN", "En attente administrateur"),
                    ("FAILED", "Échoué"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="bureau",
            constraint=models.UniqueConstraint(
                fields=("batiment", "numero"), name="unique_numero_bureau_par_batiment"
            ),
        ),
    ]
