# Generated by Django 6.0.5 on 2026-05-29 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBatiment', '0002_paiementmethode_remove_bureau_typebureau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bureaux', to='gestionBatiment.niveau'),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bureaux', to='gestionBatiment.typebureau'),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='unite',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='date_debut',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='date_fin',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrat', to='gestionBatiment.reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_debut',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_fin',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.DeleteModel(
            name='Facture',
        ),
    ]
