# Generated by Django 6.0.5 on 2026-05-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBatiment', '0004_alter_contrat_date_debut_alter_contrat_date_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='date_debut',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='date_fin',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_debut',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_fin',
            field=models.DateField(null=True, blank=True),
        ),
    ]
