# Generated by Django 6.0.5 on 2026-05-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBatiment', '0005_alter_contrat_date_debut_alter_contrat_date_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
