# Generated by Django 6.0.5 on 2026-06-02 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBatiment', '0007_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='gestionBatiment.bureau')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='gestionBatiment.client')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Equipement',
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionBatiment.paiementmethode', verbose_name='Mode de paiement'),
        ),
        migrations.DeleteModel(
            name='Maintenance',
        ),
    ]
