# Generated by Django 6.0.5 on 2026-06-19 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBatiment', '0007_alter_paiement_unique_together_paiement_annee_paye_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paiement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='paiement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payé'), ('PENDING_ADMIN', 'En attente administrateur'), ('FAILED', 'Échoué')], default='PENDING', max_length=20),
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='annee_paye',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='mois_paye',
        ),
    ]
