# Generated by Django 6.0.5 on 2026-06-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBatiment', '0008_location_delete_category_delete_equipement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typebureau',
            name='espace',
            field=models.FloatField(default=0.0, help_text='Espace en m² par défaut pour ce type'),
        ),
        migrations.AddField(
            model_name='typebureau',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Prix calculé automatiquement en fonction de l'espace et de l'unité", max_digits=10),
        ),
        migrations.AddField(
            model_name='typebureau',
            name='unite',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Prix unitaire par défaut pour ce type', max_digits=10),
        ),
    ]
