# Generated by Django 6.0.5 on 2026-06-02 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBatiment', '0009_typebureau_espace_typebureau_prix_typebureau_unite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typebureau',
            name='prix',
        ),
    ]
