# Generated by Django 6.0.5 on 2026-06-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBatiment', '0010_remove_contrat_type_facturation_batiment_periodicite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='document_attestation_caution',
            field=models.FileField(blank=True, null=True, upload_to='contrats/documents/'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='document_autre',
            field=models.FileField(blank=True, null=True, upload_to='contrats/documents/'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='document_contrat_signe',
            field=models.FileField(blank=True, null=True, upload_to='contrats/documents/'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='document_justificatif_domicile',
            field=models.FileField(blank=True, null=True, upload_to='contrats/documents/'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='document_piece_identite',
            field=models.FileField(blank=True, null=True, upload_to='contrats/documents/'),
        ),
        migrations.DeleteModel(
            name='DocumentContrat',
        ),
    ]
