# Generated by Django 6.0.5 on 2026-06-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBatiment', '0010_remove_typebureau_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bureau',
            name='unite',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
