# Generated by Django 6.0.5 on 2026-06-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestionBatiment", "0011_contrat_document_attestation_caution_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contrat",
            name="document_attestation_caution",
        ),
        migrations.RemoveField(
            model_name="contrat",
            name="document_autre",
        ),
        migrations.RemoveField(
            model_name="contrat",
            name="document_justificatif_domicile",
        ),
        migrations.RemoveField(
            model_name="contrat",
            name="document_piece_identite",
        ),
    ]
