# Generated by Django 6.0.5 on 2026-06-02 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBatiment', '0011_alter_bureau_unite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typebureau',
            name='espace',
        ),
        migrations.RemoveField(
            model_name='typebureau',
            name='unite',
        ),
    ]
