# Generated by Django 6.0.5 on 2026-06-30 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionBatiment", "0012_remove_contrat_document_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contrat",
            name="reservation",
        ),
        migrations.AddField(
            model_name="reservation",
            name="contrat",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservation",
                to="gestionBatiment.contrat",
            ),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="document_contrat_signe",
            field=models.FileField(
                blank=True,
                help_text="Document du contrat signé (PDF, image, etc.)",
                null=True,
                upload_to="contrats/documents/",
            ),
        ),
    ]
