# Generated by Django 6.0.5 on 2026-06-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBatiment', '0012_remove_typebureau_espace_remove_typebureau_unite'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
