# Generated by Django 6.0.5 on 2026-06-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBatiment', '0013_contrat_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='mode_paiement',
        ),
        migrations.AddField(
            model_name='paiement',
            name='mode',
            field=models.CharField(choices=[('CASH', 'Espèces'), ('CARD', 'Carte bancaire'), ('TRANSFER', 'Virement bancaire')], default='CASH', max_length=20),
        ),
        migrations.DeleteModel(
            name='paiementMethode',
        ),
    ]
