# Generated by Django 6.0.5 on 2026-07-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestionBatiment",
            "0014_remove_reservation_contrat_contrat_reservation_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batiment",
            name="periodicite",
        ),
    ]
