# Generated by Django 6.0.5 on 2026-06-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBatiment', '0015_paiement_contrat_paiement_statut_alter_batiment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='montant',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
