# Generated by Django 6.0.5 on 2026-06-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBatiment', '0016_alter_contrat_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
