# Generated by Django 6.0.5 on 2026-06-09 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBatiment', '0018_alter_reservation_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='gestionBatiment.client'),
        ),
    ]
