# Generated by Django 6.0.5 on 2026-06-09 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBatiment', '0019_alter_reservation_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='location',
        ),
        migrations.AddField(
            model_name='paiement',
            name='location_liee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='gestionBatiment.location'),
        ),
    ]
