# Generated by Django 6.0.5 on 2026-06-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBatiment', '0020_remove_paiement_location_paiement_location_liee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paiement',
            old_name='location_liee',
            new_name='location',
        ),
    ]
