# Generated by Django 6.0.5 on 2026-06-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBatiment', '0021_rename_location_liee_paiement_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('MANAGER', 'Gestionnaire'), ('CLIENT', 'Personnel')], default='CLIENT', max_length=15),
        ),
    ]
