# Generated by Django 6.0.5 on 2026-06-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBatiment', '0022_client_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('TRAVAILLEUR', 'Travailleur'), ('MANAGER', 'Gestionnaire'), ('CLIENT', 'Personnel')], default='CLIENT', max_length=15),
        ),
    ]
